services:
  - type: web
    name: life-end-voting-app
    runtime: node
    runtimeVersion: 22.x
    rootDir: 3.0
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
